allowBuilds:
  "@ffmpeg-installer/linux-x64": false
  "@ffmpeg-installer/linux-ia32": false
  "@ffmpeg-installer/darwin-x64": false
  "@ffmpeg-installer/win32-ia32": false
  "@ffmpeg-installer/win32-x64": false
  "@ffmpeg-installer/ffmpeg": false
  "@ffmpeg-installer/linux-arm": false
  "@ffmpeg-installer/linux-arm64": false
  "@ffmpeg-installer/darwin-arm64": false
  esbuild: false
  protobufjs: false
  sharp: false
